apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: social-service
  template:
    metadata:
      labels:
        app: social-service
    spec:
      containers:
        - name: social-service
          image: deelish/social-service:latest
          imagePullPolicy: Never  
          ports:
            - containerPort: 3003
          env:
            - name: PORT
              value: "3003"
            - name: DB_PATH
              value: /data/social.db
            - name: AUTH_SERVICE_URL
              value: http://auth-service:3001
          volumeMounts:
            - name: social-data
              mountPath: /data
      volumes:
        - name: social-data
          hostPath:
            path: /data/deelish/social      # path on the Docker Desktop VM
            type: DirectoryOrCreate
---
apiVersion: v1
kind: Service
metadata:
  name: social-service
spec:
  selector:
    app: social-service
  ports:
    - port: 3003
      targetPort: 3003